# Generated by Django 5.2.7 on 2025-12-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='places.place'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
