# Generated by Django 5.2.9 on 2025-12-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Used for public URLs.', max_length=160, null=True, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographic latitude for map links.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographic longitude for map links.', max_digits=9, null=True)),
                ('facility_type', models.CharField(choices=[('GYM', 'Gym'), ('STUDIO', 'Studio'), ('SWIM', 'Swimming Pool'), ('OUTDOOR', 'Outdoor'), ('WELLNESS', 'Wellness'), ('COURT', 'Court')], default='GYM', max_length=32)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('highlight_score', models.PositiveSmallIntegerField(default=0, help_text='Higher scores surface first in recommendations.')),
                ('accent_color', models.CharField(blank=True, help_text='CSS color shorthand (e.g. #7FEB45).', max_length=9)),
                ('hero_image', models.CharField(blank=True, help_text='Relative static path or absolute URL for hero visuals.', max_length=255)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rating_avg', models.FloatField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='places_plac_slug_1928e6_idx'), models.Index(fields=['facility_type', '-highlight_score'], name='places_plac_facilit_92006c_idx')],
            },
        ),
    ]
