# Generated by Django 5.2.7 on 2025-10-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='accent_color',
            field=models.CharField(blank=True, help_text='CSS color shorthand (e.g. #7FEB45).', max_length=9),
        ),
        migrations.AddField(
            model_name='place',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='facility_type',
            field=models.CharField(choices=[('GYM', 'Gym'), ('STUDIO', 'Studio'), ('SWIM', 'Swimming Pool'), ('OUTDOOR', 'Outdoor'), ('WELLNESS', 'Wellness'), ('COURT', 'Court')], default='GYM', max_length=32),
        ),
        migrations.AddField(
            model_name='place',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='hero_image',
            field=models.CharField(blank=True, help_text='Relative static path or absolute URL for hero visuals.', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='highlight_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher scores surface first in recommendations.'),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for public URLs.', max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='place',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tagline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['slug'], name='places_plac_slug_1928e6_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['facility_type', '-highlight_score'], name='places_plac_facilit_92006c_idx'),
        ),
    ]
