# Generated by Django 5.2.7 on 2025-10-18 11:19

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Place = apps.get_model("places", "Place")
    for place in Place.objects.filter(slug__isnull=True):
        base = slugify(place.name) or "place"
        candidate = base
        counter = 1
        while Place.objects.filter(slug=candidate).exclude(pk=place.pk).exists():
            counter += 1
            candidate = f"{base}-{counter}"
        place.slug = candidate
        place.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_place_accent_color_place_amenities_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
