# Generated by Django 5.2.7 on 2025-10-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_review_reviewlike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Geographic latitude for map links.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Geographic longitude for map links.",
                max_digits=9,
                null=True,
            ),
        ),
    ]
