# Generated by Django 5.2.8 on 2025-11-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlike',
            name='review',
        ),
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
