# Generated by Django 5.2.7 on 2025-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="calendly_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainer",
            name="price_per_session",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
